# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminuevos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=150, verbose_name='usuario')),
                ('client_secret', models.CharField(max_length=150, verbose_name='contrase\xf1a')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semi_account', to=settings.AUTH_USER_MODEL, verbose_name='Credenciales de seminuevos')),
            ],
            options={
                'verbose_name': 'cuenta de seminuevos',
                'verbose_name_plural': 'cuentas de seminuevos',
            },
        ),
    ]
