# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminuevos', '0002_semiaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semiaccount',
            name='user',
        ),
    ]
