# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminuevos', '0004_auto_20170420_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semiaccount',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='semiaccount',
            name='client_secret',
        ),
    ]
